package LearningReadTextfile;
import java.io.*;
import java.util.Scanner;


public class TextFile  {
	
	public static void main(String args[]) throws FileNotFoundException
	{
	
	File f1 = new File("testing.txt");
	Scanner sc = new Scanner(f1) ;
	while(sc.hasNext())
	{
		String s = sc.next();
		System.out.println(s);
	}
	sc.close();
	
}
	}

/*When you run the program, the "word.txt" file needs to be in the same 
directory as the .class file generated by the compiler, not the .java file. In an IDE like Netbeans, put the file 
in the project folder, not the source folder */


